language: elixir
matrix:
  include:
    - otp_release: 21.1
      elixir: 1.7.3
    - otp_release: 20.3
      elixir: 1.7.3
    - otp_release: 21.1
      elixir: 1.6.6
    - otp_release: 20.3
      elixir: 1.6.6
    - otp_release: 19.3
      elixir: 1.6.6
    - otp_release: 20.3
      elixir: 1.5.3
    - otp_release: 19.3
      elixir: 1.5.3
    - otp_release: 20.1
      elixir: 1.4.5
    - otp_release: 19.3
      elixir: 1.4.5
    - otp_release: 18.3
      elixir: 1.4.5
sudo: false
before_script:
  - mix deps.get --only test
script:
  - mix test
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
